name: Build
on: push
jobs:
  build:
    name: Deploy html
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
        clean: true # Clean destination before deploy files
